FROM golang:1.21.6 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./


RUN ls -a
RUN CGO_ENABLED=0 GOOS=linux go build -o /ecomsvc ./cmd/app

FROM build-stage AS run-test-stage
RUN go test -v ./...

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /ecomsvc /ecomsvc

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/ecomsvc"]